from django.conf.urls.defaults import *
#from students import views
# The next two lines enable the admin and load each admin.py file:
from django.views.generic.simple import direct_to_template
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/ams/home/', 'ams.views.admin_home'),
    (r'^admin/(.*)', admin.site.root),
    (r'^marks_add/', 'students.views.marks_add'),
    (r'^attendance_add/', 'students.views.attendance_add'),
    (r'^report/', 'students.views.report'),
    (r'^ams/', 'ams.views.get_barcode'),
    (r'^leave/', 'ams.views.app_leave'),
    (r'^leave_report/', 'ams.views.report_leave'),
    (r'^ams_report/', 'ams.views.monthly_report'),
    (r'^ams_daily_report/', 'ams.views.daily_report'),
    (r'^ams_display/', 'ams.views.ams_display'),
    (r'^fee/', 'fees.views.fee_receipt'),
    (r'^fee_receipt/', 'fees.views.reprint_receipt'),
    (r'^fee_report/', 'fees.views.fee_report'),
    (r'^reportPDF/', 'students.views.reportPDF'),
    (r'^certificatePDF/', 'students.views.certificatePDF'),
    (r'^cardsPDF/', 'students.views.cardsPDF'),
    (r'^schoolLeavingPDF/', 'students.views.schoolLeavingPDF'),
    (r'^fee_collection/', 'fees.views.fee_collection'),
    #(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^ams_dayrules/', 'ams.views.add_dayrules'),
    (r'^competition_add/', 'students.views.competition_add'),
    (r'^elocution_add/', 'students.views.elocution_add'),
    (r'^project_add/', 'students.views.project_add'),
    (r'^abhivyaktivikas_add/', 'students.views.abhivyaktivikas_add'),
    (r'^competitiveexam_add/', 'students.views.competitiveexam_add'),
    (r'^socialactivity_add/', 'students.views.socialactivity_add'),
    (r'^physicalfitnessinfo_add/', 'students.views.physicalfitnessinfo_add'),
    (r'^workexperience_add/', 'students.views.workexperience_add'),
    (r'^physicaleducation_add/', 'students.views.physicaleducation_add'),
    (r'^thinkingskill_add/', 'students.views.thinkingskill_add'),
    (r'^socialskill_add/', 'students.views.socialskill_add'),
    (r'^emotionalskill_add/', 'students.views.emotionalskill_add'),
    (r'^attitudetowardsschool_add/', 'students.views.attitudetowardsschool_add'),
    (r'^values_add/', 'students.views.values_add'),
    (r'^medicalreport_add/', 'students.views.medicalreport_add'),    
    (r'^names_sheet/','students.views.generate_name_columns'),
    (r'^display_report/(?P<regno>\d+)/(?P<year>\d{4}\-\d{4})','students.views.display_report'),
    ##(r'^accounts/', include('registration.backends.default.urls')),
    (r'^accounts/', include('registration.urls')),
    (r'^$', direct_to_template,  { 'template': 'index.html' }, 'index'),
    (r'^pravesh/add', 'pravesh.views.add'),
    (r'^pravesh/hallticket/(\d+)/?$','pravesh.views.display_hallticket'),
    (r'^pravesh/student/(\d+)/edit/?$','pravesh.views.edit'),
    (r'^pravesh/generate_hallticket','pravesh.views.generate_hallticket'),
    (r'^pravesh/generate_report','pravesh.views.generate_classreport'),
    (r'^pravesh/?','pravesh.views.index'),
    #(r'^useradd/', views.user_add),
    # ... the rest of your URLs here ...
)
